### ISSUE TITLE
有关face-api.js extension的安装

### ISSUE THREAD

**Issue by mickwubs97** [Scratch3Lab/scratch3_knn#6]
我想提一个可能和这个repo关系不大的问题。
我在成功添加scratch的knn模块以后一直在尝将face-api.js模块（https://github.com/justadudewhohacks/face-api.js）添加到scratch3中。

但现在只做到了成功导入模型，代码如下（使用loadFromUri）：
![image](https://user-images.githubusercontent.com/58356619/74395137-8342e580-4e49-11ea-9830-767d06b5e953.png)
可以看出，这主要是依据本repo中给出的index框架进行的进一步构架。根据console中的结果，我已经成功载入了上述4个网络。

另外，根据https://www.youtube.com/watch?v=CVClHLwv-4I （需要fq）中给出的教程和提供的代码： https://github.com/WebDevSimplified/Face-Detection-JavaScript 进行了初步测试。结论是单独运行（工程中只包括上述repo中的index.html、face-api.min.js、script.js和model文件夹）时，能正确识别结果。

于是我尝试将script.js中的代码加入到face-api extension 对应的 index中，如下：
![image](https://user-images.githubusercontent.com/58356619/74396114-0a915880-4e4c-11ea-80b1-caff8b3fee36.png)

但当点击face-api模块中的faceDetection块时，console报错如下：
![image](https://user-images.githubusercontent.com/58356619/74396215-475d4f80-4e4c-11ea-81f7-026644d680c3.png)
即：
    index.js:736 Uncaught TypeError: Cannot read property 'addEventListener' of null
    at Scratch3faceapi.faceDection (index.js:736)
    at extension-manager.js:428
    at blockInfo.func (extension-manager.js:435)
    at execute (execute.js:523)
    at Sequencer.stepThread (sequencer.js:212)
    at Sequencer.stepThreads (sequencer.js:128)
    at Runtime._step (runtime.js:2031)
    at runtime.js:2552

查询相关资料发现可能是 const video = document.getElementById('img') 一项使用不当，原repo（https://github.com/WebDevSimplified/Face-Detection-JavaScript ）中是在index.html中加入了video 元素，直接在script.js中使用了const video = document.getElementById('video')进行调用处理：
<body>
  <video id="video" width="720" height="560" autoplay muted></video>
</body>

所以我现在主要想原repo中 const video = document.getElementById('video') 语句中的id为video的video元素对应现在Scratch3的index.html中的哪个元素，或者说我应该用哪个元素id替换'video'才能调用Scratch3网页中的视频信息进行进一步的处理？或者我需要构建一个新元素吗？（根据 https://github.com/justadudewhohacks/face-api.js 中所言我需要一个html img 或者 video 或者 canvas元素作为输入（input）:
![image](https://user-images.githubusercontent.com/58356619/74396842-2e559e00-4e4e-11ea-9f20-d2ac31cc7ddf.png)
所以我现在想问一下Scratch3的index.html中哪里有这样的元素可以直接调用作为input？

或者我的思路是有问题的？那么我能否从这里得到一些建议，我觉得那样的话也会对我下一步的方向有很大的启发。

或者我需要进一步提供和其他有关信息吗？我的邮箱如下：
sxtgwzz@163.com

十分感谢，希望能得到回复。

**Comment by summerscar** [comment]
可以在开启摄像头的函数中获取到 video 数据
```
 videoToggle(args) {
        const state = args.VIDEO_STATE;
        this.globalVideoState = state;
        if (state === VideoState.OFF) {
            this.runtime.ioDevices.video.disableVideo();
        } else {
            this.runtime.ioDevices.video.enableVideo().then(() => {
                // 获得video数据
                this.video = this.runtime.ioDevices.video.provider.video
            });
            // Mirror if state is ON. Do not mirror if state is ON_FLIPPED.
            this.runtime.ioDevices.video.mirror = state === VideoState.ON;
        }
    }
```
调用Faceapi时，直接将video传入即可
```
faceapi.detectSingleFace(this.video, new faceapi.TinyFaceDetectorOptions({ inputSize: 224, scoreThreshold: 0.5 }))
```

**Comment by summerscar** [comment]
也可以参考官方的视频侦测（video_sensing）插件，循环获取当前的画面截图传入faceapi去处理

_loop 方法中
```
const frame = this.runtime.ioDevices.video.getFrame({
                format: Video.FORMAT_IMAGE_DATA,
                dimensions: Scratch3FaceDetect .DIMENSIONS
            });
```

**Comment by mickwubs97** [comment]
@summerscar ,谢谢您的回复。
我在index.js中按照第一个方法进行了尝试。
在videoToggle 中进行了修改：
![image](https://user-images.githubusercontent.com/58356619/74430279-8cf33a00-4e97-11ea-92ee-c1531f340d19.png)
在faceDetection（之前该函数命名好像有问题）函数中保留了script.js中的人脸提取和结果显示的代码：
![image](https://user-images.githubusercontent.com/58356619/74430534-0428ce00-4e98-11ea-943a-568931bf72a1.png)
我的基本想法是在videoToggle中获得video，然后再在videoDetection中调用faceapi的API进行识别和显示。
但我目前在console中遇到的问题是当点击faceDetection模块时，控制台报错：
index.js:733 Uncaught ReferenceError: video is not defined
    at Scratch3faceapi.faceDetection (index.js:733)
    at extension-manager.js:428
    at blockInfo.func (extension-manager.js:435)
    at execute (execute.js:523)
    at Sequencer.stepThread (sequencer.js:212)
    at Sequencer.stepThreads (sequencer.js:128)
    at Runtime._step (runtime.js:2031)
    at runtime.js:2552

我猜测可能是video作用域的问题。我后来又尝试了把faceDetection中的代码转移到videoToggle中，但并没有出现预期效果。而且这个videoToggle是自动会循环执行的吗？我知道_loop好像是自动循环执行的，但第二种方法的frame visual studio code 显示它的类型不是HTMLElement，我觉得要在Scratch3平台实现script.js中的识别和显示功能，那么输入应该是HTMLElemnt（和之前 https://github.com/WebDevSimplified/Face-Detection-JavaScript 中的一致），所以没有进一步尝试。而如果videoToggle不是自动循环执行而是只在初始化时执行一次的话，那么为了实现动态人脸识别，是不是需要从别处提取video或者在faceDetection中加入videoToggle中的部分代码，让提取和识别都在循环执行，或许能避免上述“video is not defined”的错误？或者就是作用域的问题，this.video只在videoToggle中有效？而如果是单纯作用域的问题的话，我该怎样才能在faceDetection中使用videoToggle或者_loop中获得的元素？

也可能是我对于index的结构了解还没有进行足够深入地理解，但我觉得或许再提一个issue能比较好的解决目前的问题……然后再进一步了解index.js……

希望能得到回复。我也会尽量继续做一些尝试，如果有结果及时反馈。

PS，上图中涉及的两端代码如下：

videoToggle(args) {
        const state = args.VIDEO_STATE;
        this.globalVideoState = state;
        if (state === VideoState.OFF) {
            this.runtime.ioDevices.video.disableVideo();
        } else {
            this.runtime.ioDevices.video.enableVideo().then(() => {
                // 获得video数据
                this.video = this.runtime.ioDevices.video.provider.video
            });
            // Mirror if state is ON. Do not mirror if state is ON_FLIPPED.
            this.runtime.ioDevices.video.mirror = state === VideoState.ON;
        }	
    }

faceDetection()
	{
		if (this.globalVideoState === VideoState.OFF) {
            console.log('请先打开摄像头')
            return
        }
        
		//const video = document.getElementsByTagName('frame')
        video.addEventListener('play', () => {
            const canvas = faceapi.createCanvasFromMedia(video)
            document.body.append(canvas)
            const displaySize = {width: video.width,height: video.height}
            faceapi.matchDimensions(canvas, displaySize)
            setInterval(async () => {
              const detections = await faceapi.detectAllFaces(video, new faceapi.TinyFaceDetectorOptions()).withFaceLandmarks().withFaceExpressions()
              const resizedDetections = faceapi.resizeResults(detections, displaySize)
              canvas.getContext('2d').clearRect(0, 0, canvas.width, canvas.height)
              faceapi.draw.drawDetections(canvas, resizedDetections)
              faceapi.draw.drawFaceLandmarks(canvas, resizedDetections)
              faceapi.draw.drawFaceExpressions(canvas, resizedDetections)
            }, 100)
          })
		}

**Comment by mickwubs97** [comment]
可能是有点着急了，我觉得细节上这个问题我自己解决吧。再次感谢，最后有结果我再贴上去。

**Comment by AyazRahman** [comment]
Hi,
After passing the video feed, when it comes to drawing on the canvas, the output is flipped. Was wondering how you fixed that or how you implemented the drawing part?

**Comment by mickwubs97** [comment]
Hi, it seems that the face-api will use a mirror position for the output box. I checked the size of the canvas and use the size of the canvas to minius the original position, so that to inverse this filped position. Hope it helps.

**Comment by AyazRahman** [comment]
Hi, thanks for replying. I don't follow what you are saying. Is it possible to share a code snippet? That might help me to understand.

**Comment by mickwubs97** [comment]
I think maybe this picture will assist you. you need to find the parameters which indicates the x and y in faceapi,  in order to shift the rectangle box from position a'(flipped position) to position  a(desired position) , you need to find the W (width) and H (height) of the window, which can also be found in faceapi document, use the subtraction and map the flipped position to the desired position as showed in the picture.
![20210115_063043](https://user-images.githubusercontent.com/58356619/104690178-de392880-56fb-11eb-81cd-7adc4d383431.jpg)

**Comment by AyazRahman** [comment]
Ok, that makes sense. So I believe you have to use a custom draw function instead of the built-in function faceapi.draw.drawDetections(canvas, resizedDetections). Is that correct?

**Comment by mickwubs97** [comment]
Yes, because I have to customize the size of the canvas instead of using the default size.
