### ISSUE TITLE
关于posenet模型加载的一点问题

### ISSUE THREAD

**Issue by YIN-jw** [Scratch3Lab/scratch3_knn#8]
十分抱歉再次打扰您，我在尝试安装posenet插件，对于如何导入模型这里一直没有弄得特别明白，在这个地方卡了很长时间，所以特来请教，希望您能给我一点建议。
       插件开头的安装posenet插件的步骤和安装knn插件的相似，参考codelab的posenet插件将getinfo()中的内容完成，能够正确弹出积木块。在加载模型时参考的官方的readme，做了如下的添加和修改：
在index的开头修改如下：
`//import * as posenet from '@tensorflow-models/posenet';
//const tf = require('@tensorflow/tfjs');
const posenet = require('@tensorflow-models/posenet');
const tf = require('@tensorflow/tfjs-core');
//const tf = require('@tensorflow/tfjs-converter');
`
在index的结尾修改如下：
`    async posenetInit () {
        this.posenet = await posenet.load({
	    architecture: 'MobileNetV1',
            outputStride: 16,
            inputResolution: { width: 640, height: 480 },
            multiplier: 0.75
        }); 
		console.log(this.posenet)
    }`
    通过isloaded积木块能显示True,我理解的是模型已经成功加载了。
` isloaded() {return Boolean(this.posenet) }`
      在检测姿态的部分，在开启摄像头的部分获取video数据，再直接传入函数中，这样得到的pose的结果是：
![5](https://user-images.githubusercontent.com/59693293/75407974-57e2ef00-594f-11ea-841e-57928d96cb93.png)
![6](https://user-images.githubusercontent.com/59693293/75407980-5d403980-594f-11ea-8051-c1661b05ff18.png)
       按照readme中的说明，应该是可以输出每个部位的坐标，但是不清楚为什么我这里结果显示不出坐标。在查找原因中发现，控制台的network中只加载了这三个文件，不知道是不是模型没有完全加载进去。目前有想到加载静态文件的办法，但是也不清楚具体该如何实施。希望您能提供一些建议，万分感谢！
      开启摄像头的程序和检测姿态的程序附在下方：
![3](https://user-images.githubusercontent.com/59693293/75408100-c88a0b80-594f-11ea-8c5e-cc4cab93d601.png)
![4](https://user-images.githubusercontent.com/59693293/75408106-cb84fc00-594f-11ea-877e-808c8355179b.png)
       再次感谢！

**Comment by YIN-jw** [comment]
图片可能没有添加上，将代码附在下方：
开启摄像头部分的程序：
`    videoToggle(args) {
        const state = args.VIDEO_STATE;
        this.globalVideoState = state;
        if (state === VideoState.OFF) {
            this.runtime.ioDevices.video.disableVideo();
        } else {
            this.runtime.ioDevices.video.enableVideo().then(() => {
				this.video = this.runtime.ioDevices.video.provider.video
				console.log('this.video got')
				console.log(this.video)
				//获得video数据
			})
            // Mirror if state is ON. Do not mirror if state is ON_FLIPPED.
            this.runtime.ioDevices.video.mirror = state === VideoState.ON;
        }
    }`
检测姿态的程序：
`    poseConfidence(args,util) {
		if (this.globalVideoState === VideoState.OFF) {
            alert('请先打开摄像头')
            return
        }
		this.timer = setInterval(async () => {
			const imageScaleFactor = 0.50;
                        const flipHorizontal = false;
                        const outputStride = 16;
                        const imageElement = this.video；
			const net =this.posenet;
			const pose = await net.estimateSinglePose(imageElement, imageScaleFactor, flipHorizontal, outputStride);
		console.log(pose)},1000); 
	}`
   控制台输出的结果：
  keypoints: Array(17)
0:
score: 0.9740554094314575
part: "nose"
position:
x: 0
y: 0
__proto__: Object
__proto__: Object
1:
score: 0.9785901308059692
part: "leftEye"
position: {x: 0, y: 0}
__proto__: Object
...
network中加载的文件是：
model-stride16.json;
group1-shard1of2.bin;
group1-shard2of2.bin

**Comment by summerscar** [comment]
这个情况我也没见过 去官方提个issues呢
https://github.com/tensorflow/tfjs/issues

**Comment by YIN-jw** [comment]
> 这个情况我也没见过 去官方提个issues呢
> https://github.com/tensorflow/tfjs/issues

**Comment by YIN-jw** [comment]
找到原因啦~
需要给this.video添加宽度和高度
+this.video.width=500;
+this.video.height=500;
就能出来结果了：
![111](https://user-images.githubusercontent.com/59693293/75603264-c2d72600-5b07-11ea-9c28-8e834552e1d6.png)
再次感谢~
